version: 2.1
orbs:
    sbt: jcouyang/sbt@0.1.0
workflows:
  version: 2
  test:
    jobs:
      - sbt/test
  release:
    jobs:
      - sbt/test:
          filters:
            tags:
              only: /^v[0-9.]+.*/
            branches:
              ignore: /.*/
      - sbt/release:
          requires:
            - sbt/test
          filters:
            tags:
              only: /^v[0-9.]+.*/
            branches:
              ignore: /.*/
